/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117253-g8e76c99301-20240929"
#endif /* AVUTIL_FFVERSION_H */
